# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50962a9dbecfbb7afd2af58c50c2f2f4"
application_url = "https://infections-pix-seas-renewal.trycloudflare.com"
embedded = true
name = "badge-app-remix"
handle = "badge-app-remix"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://infections-pix-seas-renewal.trycloudflare.com/auth/callback",
  "https://infections-pix-seas-renewal.trycloudflare.com/auth/shopify/callback",
  "https://infections-pix-seas-renewal.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
